ShopProject/ShopProject.MVC/Controllers/ProductController.cs
using ShopProject.Business.RepositoryFolder;
using ShopProject.Data.POCOs;
using ShopProject.MVC.Filters;
using ShopProject.MVC.FormDatas;
using ShopProject.MVC.ModelBinders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ShopProject.MVC.Controllers
{
    
    public class ProductController : BaseController
    {
        IRepository<Product> productRepository = uow.GetRepository<Product>();
        IRepository<Category> categoryRepository = uow.GetRepository<Category>();
        IRepository<ProductQuantity> productQuantityRepository = uow.GetRepository<ProductQuantity>();
        IRepository<Purchase> purchaseRepository = uow.GetRepository<Purchase>();
        IRepository<Address> addressRepository = uow.GetRepository<Address>();
        IRepository<User> userRepository = uow.GetRepository<User>();
        IRepository<ShoppingCart> shoppingCartRepository = uow.GetRepository<ShoppingCart>();

        [AdminRoleAuthentication]
        public ActionResult CreateProduct()
        {
            TempData["Categories"] = categoryRepository.GetAll().Select(s => new SelectListItem
            {
                Value = s.ID.ToString(),
                Text = s.Name,
                Selected = true,
            }).ToList();
            return View();
        }

        [AdminRoleAuthentication]
        [HttpPost]
        public ActionResult CreateProduct([ModelBinder(typeof(CreateProductModelBinder))] Product product)
        {
            if (ModelState.IsValid)
            {
                productRepository.Add(product);
                uow.SaveChanges();
                TempData["Status"] = "success";
                TempData["Message"] = "Record added successfully!";
            }
            else
            {
                TempData["Status"] = "danger";
                TempData["Message"] = "Record could not added successfully!!!";
            }
            return View();
        }

        public ActionResult ProductList(string filterString,string categoryName,string sortMethod)
        {
            if (String.IsNullOrEmpty(filterString))
            {
                TempData["CategoryName"] = categoryName;

                IEnumerable<Product> Prods = new List<Product>();
                if (String.IsNullOrEmpty(categoryName))
                {
                    Prods = productRepository.GetAll();
                }
                else
                {
                    Prods = productRepository.GetBy(w => w.Category.Name == categoryName);
                }

                switch (sortMethod)
                {
                    case "azName":
                        Prods = Prods.OrderBy(w => w.Name);
                        break;

                    case "zaName":
                        Prods = Prods.OrderByDescending(w => w.Name);
                        break;

                    case "lhPrice":
                        Prods = Prods.OrderBy(o => o.Price);
                        break;

                    case "hlPrice":
                        Prods = Prods.OrderByDescending(o => o.Price);
                        break;
                }

                ICollection<ProductFormData> pfdList = new List<ProductFormData>();

                foreach (var production in Prods)
                {
                    ProductFormData pfd = new ProductFormData();
                    pfd.ID = production.ID;
                    pfd.Base64Image = "data:image/png;base64," + Convert.ToBase64String(production.ProductImage);
                    pfdList.Add(pfd);
                }

                ProductListFormData plfm = new ProductListFormData
                {
                    Categories = categoryRepository.GetAll(),
                    Products = Prods,
                    ProductFormDatas = pfdList
                };
                return View(plfm);
            }
            else
            {
                TempData["CategoryName"] = categoryName;

                IEnumerable<Product> Prods;
                if (categoryName != null && categoryName!="")
                {
                     Prods = productRepository.GetBy(w => w.Name.ToLower().Contains(filterString.ToLower()) && w.Category.Name == categoryName).ToList();
                }
                else
                {
                     Prods = productRepository.GetBy(w => w.Name.ToLower().Contains(filterString.ToLower())).ToList();
                }
                switch (sortMethod)
                {
                    case "azName":
                        Prods = Prods.OrderBy(w => w.Name);
                        break;

                    case "zaName":
                        Prods = Prods.OrderByDescending(w => w.Name);
                        break;

                    case "lhPrice":
                        Prods = Prods.OrderBy(o => o.Price);
                        break;

                    case "hlPrice":
                        Prods = Prods.OrderByDescending(o => o.Price);
                        break;
                }

                ICollection<ProductFormData> pfdList = new List<ProductFormData>();

                foreach (var production in Prods)
                {
                    ProductFormData pfd = new ProductFormData();
                    pfd.ID = production.ID;
                    pfd.Base64Image = "data:image/png;base64," + Convert.ToBase64String(production.ProductImage);
                    pfdList.Add(pfd);
                }

                ProductListFormData plfm = new ProductListFormData
                {
                    Categories = categoryRepository.GetAll(),
                    Products = Prods,
                    ProductFormDatas = pfdList
                };
                return View(plfm);

            }


            
        }

        public ActionResult ProductDetails(int ID)
        {
            Product selectedProduct = productRepository.GetById(ID);

            ICollection<Product> AllProductsInCategory = productRepository.GetBy(w => w.CategoryID == selectedProduct.CategoryID && w.ID != ID).ToList();
            ICollection<ProductFormData> pfdList = new List<ProductFormData>();

            ProductFormData pfdInit = new ProductFormData();
            pfdInit.ID = selectedProduct.ID;
            pfdInit.Base64Image = "data:image/png;base64," + Convert.ToBase64String(selectedProduct.ProductImage);
            pfdList.Add(pfdInit);

            ICollection<Product> finalizedProducts = new List<Product>();

            for (int i = 0; i < 4; i++) //get 4 random if there are 4 else return all existed
            {
                if (AllProductsInCategory.Count() != 0)
                {
                    Product randSelectedProduct = AllProductsInCategory.ElementAt(FakeData.NumberData.GetNumber(0, AllProductsInCategory.Count() - 1));

                    if (randSelectedProduct != null)
                    {
                        finalizedProducts.Add(randSelectedProduct);
                        AllProductsInCategory.Remove(randSelectedProduct);
                    }
                }
                else
                    break;
            }

            foreach (var production in finalizedProducts)
            {
                ProductFormData pfd = new ProductFormData();
                pfd.ID = production.ID;
                pfd.Base64Image = "data:image/png;base64," + Convert.ToBase64String(production.ProductImage);
                pfdList.Add(pfd);
            }

            return View(new ProductDetailsFormData() { Categories = categoryRepository.GetAll(), Product = selectedProduct, ProductFormDatas = pfdList, SameCategoryProducts = finalizedProducts });
        }

        [HttpPost]
        public JsonResult AddProductToCart(int ID)
        {
            User currentUser = Session["User"] as User;
            ShoppingCart currentShoppingCart = currentUser.ShoppingCart;

            if (currentShoppingCart.ProductQuantities.Where(w => w.ProductID == ID).Count() == 0)
            {
                Product AddedProduct = productRepository.GetById(ID);

                ProductQuantity newProductQuantity = new ProductQuantity();
                newProductQuantity.Product = AddedProduct;
                newProductQuantity.Quantity = 1;
                newProductQuantity.ShoppingCart = currentShoppingCart;

                currentShoppingCart.ProductQuantities.Add(newProductQuantity);
                currentShoppingCart.TotalPrice = SetTotalPrice(currentShoppingCart);

                productRepository.Attach(AddedProduct);


                productQuantityRepository.Add(newProductQuantity);
                try
                {
                    uow.SaveChanges();
                }
                catch (Exception ex) { }
            }
            else
            {
                currentShoppingCart.ProductQuantities.SingleOrDefault(w => w.ProductID == ID).Quantity++;
            }

            return Json("");
        }

        public double SetTotalPrice(ShoppingCart shoppingCart)
        {
            double totalPrice = 0;
            foreach (var productQuantity in shoppingCart.ProductQuantities)
            {
                totalPrice += productQuantity.Product.Price * productQuantity.Quantity;
            }
            return totalPrice;
        }

        public ActionResult DisplayShoppingCart()
        {
            return View((Session["User"] as User).ShoppingCart);
        }

        [HttpPost]
        public JsonResult GetAddressDescription(int addressID)
        {
            if (addressID == -1)
            {
                return Json("Please enter your address");
            }
            else
            {
                string addressDesc = addressRepository.SingleGetBy(w => w.ID == addressID).Description;
                return Json(addressDesc);
            }
        }

ShopProject/ShopProject.MVC/Controllers/ShopController.cs
using ShopProject.Business.RepositoryFolder;
using ShopProject.Data.POCOs;
using ShopProject.MVC.Filters;
using ShopProject.MVC.FormDatas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopProject.MVC.Controllers
{
    
    public class ShopController : BaseController
    {
        IRepository<Category> categoryRepository = uow.GetRepository<Category>();
        IRepository<Product> productRepository = uow.GetRepository<Product>();

        public ActionResult Index()
        {
            ShopIndexFormData sifd = new ShopIndexFormData();

            ICollection<Category> Categories = categoryRepository.GetAll().ToList();
            ICollection<Product> AllProducts = productRepository.GetAll().ToList();

            ICollection<ProductFormData> pfdList = new List<ProductFormData>();
            ICollection<Product> finalizedProducts = new List<Product>();

            for (int i = 0; i < 8; i++) //get 4 random if there are 4 else return all existed
            {
                if (AllProducts.Count() != 0)
                {
                    Product randSelectedProduct = AllProducts.ElementAt(FakeData.NumberData.GetNumber(0, AllProducts.Count() - 1));

                    if (randSelectedProduct != null)
                    {
                        finalizedProducts.Add(randSelectedProduct);
                        AllProducts.Remove(randSelectedProduct);
                    }
                }
                else
                    break;
            }

            foreach (var production in finalizedProducts)
            {
                ProductFormData pfd = new ProductFormData();
                pfd.ID = production.ID;
                pfd.Base64Image = "data:image/png;base64," + Convert.ToBase64String(production.ProductImage);
                pfdList.Add(pfd);
            }

            

            #region Get Random Products by Random Category 
            //foreach (var category in )
            //{

            //    for (int i = 0; i < 8; i++)
            //    {
            //        if (ProductsOfCategory.Count() != 0)
            //        {
            //            Product randProduct = ProductsOfCategory.ElementAt(FakeData.NumberData.GetNumber(0, ProductsOfCategory.Count() - 1));


            //            if (randProduct != null)
            //            {
            //                ProductFormData productFormData = new ProductFormData();
            //                productFormData.ID = randProduct.ID;
            //                productFormData.Base64Image = "data:image/png;base64," + Convert.ToBase64String(randProduct.ProductImage);
            //                productFormDataList.Add(productFormData);
            //                randProductsByCatFM.Products.Add(randProduct);
            //                ProductsOfCategory.Remove(randProduct);
            //            }
            //            else
            //                break;
            //        }
            //        else
            //            break;
            //    }

            //    randProdByCatList.Add(randProductsByCatFM);
            //}
            #endregion

            sifd.Categories = categoryRepository.GetAll();
            sifd.RandomProducts = finalizedProducts;
            sifd.ProductFormDatas = pfdList;

            return View(sifd);
        }


    }
}

ShopProject/ShopProject.MVC/Views/Product/CreateProduct.cshtml
@model ShopProject.Data.POCOs.Product

@{
    ViewBag.Title = "AddProduct";
}

<h2>AddProduct</h2>
<link href="~/ShopFrontEnd/css/bootstrap.css" rel="stylesheet" />
<script src="~/ShopFrontEnd/js/jquery-2.1.4.min.js"></script>
<script src="~/ShopFrontEnd/js/bootstrap.js"></script>
<script type="text/javascript">
    $(function () {
        $('#btnCreate').click(function () {

            var name = $('#Name').val();
            var price = $('#Price').val();
            var size = $('#Size').val();
            var categoryID = $('#Category').val();
            var image = ($('#productPhotoArea').attr('src'));
            var lastImage = image.replace(/^data:image\/(png|jpg|jpeg|PNG|JPEG);base64,/, "");

            $.ajax(
                    {
                        method: "POST",
                        url: "../Product/CreateProduct",
                        type: "json",
                        dataType: "application/json; charset=utf-8;",
                        data: { Name: name, Price: price, Size: size, CategoryID: categoryID, ImageBase64: lastImage },
                        success: function () { }
                    });

        //    $.post('http://localhost:63668/api/ProductApi/CreateProduct', { Name: name, Price: price, Size: size, CategoryID: categoryID, ImageBase64: lastImage }, function (response)
        //    { console.log(response) }, 'json');
       });

        $("#inputPhoto").change(function () {
            $('#photoInitialDescription').remove();
            readURL(this);

        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#productPhotoArea').attr('src', e.target.result);
                    $('#base64textarea').val($('#productPhotoArea').attr('src'));
                    //$('#base64textarea').val(btoa(e.target.result));
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    });
</script>
@*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@



<div class="form-horizontal">
    <h4>Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.DropDownList("Category", TempData["Categories"] as List<SelectListItem>)
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Size, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon" id="productPhotoChooseArea">Profile Photo</span>
            <label class="btn btn-default">Browse<input type="file" id="inputPhoto" /></label>
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="input-group" id="photoPreview">
            <span class="input-group-addon">Photo</span>
            <img id="productPhotoArea" width="30%" height="auto" />
            <div id="photoInitialDescription">
                NOT CHOSEN YET!
            </div>
        </div>
    </div>
    <br />
    <input type="hidden" id="base64textarea" />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Create" class="btn btn-default" id="btnCreate"/>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Back", "Index", "Shop")
</div>

ShopProject/ShopProject.MVC/Views/Product/Deneme.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deneme</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoldCount)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoldCount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>